# Generated by Django 4.0.4 on 2023-07-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mesas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesas',
            new_name='Mesa',
        ),
    ]
